# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e8c69cca99f1a28c677b13aaab3f39cce8f46f577efa12da6ae6d1c62d66dcf8d5b05adc371f6addd083c52305354b6ee5f3afab3b7f8850ba264050ab0a5fb

test:
  secret_key_base: 76617697701073fc51050048619a4888305d31a3753b62fb78c397035074bd516ea0ea0ffda7c7c39050a1b698b70679d240785a328961074cfcef9f068cc60e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
